### ISSUE TITLE
新需求🎈，戳这里👇

### ISSUE THREAD

**Issue by Ailln** [Ailln/cn2an#10]
如果你有新的需求，可以来这个 issues 中讨论。

比如：我有个关于「人民币大写」转化的需求。

**Comment by wezhyn** [comment]
我想要拼音转数字:laughing::laughing:

**Comment by HaveTwoBrush** [comment]
> 我想要拼音转数字😆😆

如果先用一个「拼音」转「中文」的库，然后再用本库可以满足你的需求吗？

**Comment by wezhyn** [comment]
> > 我想要拼音转数字laughinglaughing
> 
> 如果先用一个「拼音」转「中文」的库，然后再用本库可以满足你的需求吗？

可以，最近感觉遇上了好几种较为诡异的转化

**Comment by HaveTwoBrush** [comment]
比如说？

**Comment by OpenWaygate** [comment]
直接转换一段文本中的数字, 比如`'七十周年' -> '70周年'`

**Comment by HaveTwoBrush** [comment]
@OpenWaygate 这个需求我觉得属于库的扩展应用，暂时不考虑添加。我觉得你当前的做法就很好～

**Comment by FankLi** [comment]
比如：我的手机号是 123456 ，我有 101 块钱
转为：我的手机号是 一二三四五六 ，我有 一百零一 块钱

**Comment by HaveTwoBrush** [comment]
@FankLi 这个功能和上面 OpenWaygate 提到的差不多，希望在文本中直接转化数字。

这不属于该库的核心功能，你可以通过正则替换来解决。

下面是一个简单的 DEMO：

```python
import re
import cn2an

input_string = "我的手机号是 123456 ，我有 101 块钱"
pattern = r"[0-9]+"

output_string = re.sub(pattern, lambda x: cn2an.an2cn(x.group()), input_string)

print(output_string)
# 我的手机号是 十二万三千四百五十六 ，我有 一百零一 块钱
```

这里会出现一些问题，比如**电话号码不应该转化为十进制的数字**。

这种判断不是一些简单的规则可以搞定的，可能需要一些自然语言处理的技术介入，目前来看它超出了该项目的范围，在未来有可能会加入。

**Comment by FankLi** [comment]
> @FankLi 这个功能和上面 OpenWaygate 提到的差不多，希望在文本中直接转化数字。
> 
> 这不属于该库的核心功能，你可以通过正则替换来解决。
> 
> 下面是一个简单的 DEMO：
> 
> ```python
> import re
> import cn2an
> 
> input_string = "我的手机号是 123456 ，我有 101 块钱"
> pattern = r"[0-9]+"
> 
> output_string = re.sub(pattern, lambda x: cn2an.an2cn(x.group()), input_string)
> 
> print(output_string)
> # 我的手机号是 十二万三千四百五十六 ，我有 一百零一 块钱
> ```
> 
> 这里会出现一些问题，比如**电话号码不应该转化为十进制的数字**。
> 
> 这种判断不是一些简单的规则可以搞定的，可能需要一些自然语言处理的技术介入，目前来看它超出了该项目的范围，在未来有可能会加入。

嗯，你的解释让我明确了思路，期待此功能！

**Comment by huanggengkeng** [comment]
from cn2an import cn2an, an2cn

text = "-100"
print(an2cn(text))

text = "负一百"
print(cn2an(text))


# 负数的转换暂时也是不支持的么 ？

**Comment by HaveTwoBrush** [comment]
@huanggengkeng 暂不支持。

你可以考虑先做正负判断再调用，下个小版本我会添加这个功能。

**Comment by HaveTwoBrush** [comment]
@huanggengkeng 0.3.8 版本已经发布，添加了对负数的支持。

**Comment by huanggengkeng** [comment]
@HaveTwoBrush 谢谢哈

**Comment by huanggengkeng** [comment]
@Ailln 我现在把程序封装到docker里面，用docker compose 运行，但是在下载cn2an的时候一直报错：
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c6k7n574/cn2an/setup.py", line 5, in <module>
        from cn2an import version
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/__init__.py", line 2, in <module>
        from . import cn2an
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/cn2an.py", line 3, in <module>
        from . import utils
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/utils.py", line 3, in <module>
        import yaml
    ModuleNotFoundError: No module named 'yaml'

我的requirements文件已经包含了pyyaml 和cn2an。
gunicorn
uvicorn
loguru
pandas
sqlalchemy
redis
datetime
configparser
PyYAML>=5.1
cn2an
想问下这是怎么回事呢 ？

**Comment by posenhuang** [comment]
Can you handle `123.05亿'? Thanks!

**Comment by Ailln** [comment]
@posenhuang 近期我可能比较忙。我有个想法，你可以自己来试着自己写一下：

1. 用正则匹配到这种特殊情况，即包含小数点和中文单位。
2. 用正则将数字部分提出 number = 123.05。
3. 用 unit = cn2an.cn2an("一亿") 得到单位。
4. 将 number 和 unit 想乘得到结果。

**Comment by huanggengkeng** [comment]
测试“ cn2an(“三万亿”）,也是转化错误哦，等于 30000000000000000
cn2an("三千万亿") ，等于3000000000000000，也不对哦
@Ailln

**Comment by wsgfz** [comment]
中文人民币金额转阿拉伯数字这个功能没有哇？

是有什么坑吗？

**Comment by Ailln** [comment]
@wsgfz ”圆整“ 不是数字，因此在输入的时候需要去掉。

我会将自动去掉”圆整“作为一个功能，放在下个小版本里。

你可以先试试这样做：

```python
import cn2an

text = "伍拾贰万圆整"
new_text = text.replace("圆整", "")
result = cn2an.cn2an(new_text)
print(result)
# 520000
```

**Comment by Ailln** [comment]
@wsgfz v0.4.2 版本上线，该功能已加入，请更新后使用。

![image](https://user-images.githubusercontent.com/7982046/85910909-21ad7180-b854-11ea-9355-27d4e01533f0.png)

**Comment by SoaringTiger** [comment]
能否支持中文“**分数**”转换
三分之二 ——>  2/3
百分之五 ——> 5%  或  5/100

**Comment by Ailln** [comment]
@SoaringTiger 已经支持分数，请更新至 `v0.5.2`。

![image](https://user-images.githubusercontent.com/7982046/87075561-1fcfaf00-c253-11ea-8dc4-1161723b4a56.png)

**Comment by Kiteflyingee** [comment]
![image](https://user-images.githubusercontent.com/12490322/90332177-7d42e280-dfed-11ea-85ce-6e3525f0be55.png)
这种百分数不能转换

**Comment by Ailln** [comment]
@Kiteflyingee 收到，我会尽快支持～

**Comment by Ailln** [comment]
@Kiteflyingee `v0.5.3` 已经添加对小数和负数的转化支持。

![image](https://user-images.githubusercontent.com/7982046/90334583-42e34080-e001-11ea-8156-d4ee4cfbd176.png)

**Comment by Green-li** [comment]
transform函数对亿的转换好像有点问题。
如下字符串：
```
"约2.5亿年~6500万年"
```
理想的结果为` 250000000年~65000000年`或者`2.5e8年~6.5e7年`

另外中文的句子比如“万历十二年”，会报错，实际上应该把`十二`转化为`12`，这个能否改善呢？比如在中文的千百万等词之前如果没有数量词（百千万，一到十）等，那么这个万就忽略。

**Comment by Ailln** [comment]
@Green-li I will check it.

**Comment by Ailln** [comment]
@Green-li 不符合格式的数据不作处理，但是会打印一个警告，你觉得这样处理可以吗？

![image](https://user-images.githubusercontent.com/7982046/90502314-2d485500-e180-11ea-9887-32bfc32fa143.png)

**Comment by Green-li** [comment]
@Ailln 嗯嗯，我觉得这样比直接报错好一些。
另外，中文的`二十`还有另一种表达方式：`正德十三年戊寅五月廿六日`中的`廿六`是`26`，目前好像还不支持。

**Comment by Ailln** [comment]
@Green-li 我将在下个小版本添加对`廿`的支持。

**Comment by Green-li** [comment]
@Ailln 突然发现微软做过类似的东西了😂：https://github.com/microsoft/Recognizers-Text
在微软这个东西的基础上封装一下，可能能达到我的要求了。

**Comment by Green-li** [comment]
@Ailln 突然发现微软做过类似的东西了😂：https://github.com/microsoft/Recognizers-Text
在微软这个东西的基础上封装一下，可能能达到我的要求了。

**Comment by Ailln** [comment]
@Green-li 好的，我大致看了一下，这是一个很丰富的库，巨硬现在做开源越来越棒了！

另外，我能加你微信吗？个人有点私事想请教你一下，我的微信ID是`Ailln_`。

**Comment by mengxifeng** [comment]
三十五块八可以支持转成35.8吗

**Comment by Ailln** [comment]
@mengxifeng 你看下这样做可以解决你的问题吗？

```python
import cn2an

s = "三十五块八".replace("块", "点")

output = cn2an.cn2an(s)
# output: 35.8
```

**Comment by mengxifeng** [comment]
![1599654744819](https://user-images.githubusercontent.com/6059548/92598589-97659d00-f2db-11ea-8e3d-6af8f65006f9.jpg)
这个格式为啥不正常呢

**Comment by mengxifeng** [comment]
> @mengxifeng 你看下这样做可以解决你的问题吗？
> 
> ```python
> import cn2an
> 
> s = "三十五块八".replace("块", "点")
> 
> output = cn2an.cn2an(s)
> # output: 35.8
> ```

嗯嗯，已经解决了，感谢

**Comment by lihuacai168** [comment]
```
import cn2an
cn2an.transform('伍拾-陆拾', 'cn2an')
实际: '伍10-陆10'
期望: '50-60'

cn2an.transform('伍拾到陆拾', 'cn2an')
实际: '伍10到陆10'
期望: '50-60'
```

**Comment by Ailln** [comment]
@lihuacai168 目前 transform 对大写数字的支持很差，你可以尝试先做预处理，然后再使用 transform。

```python
import cn2an

s = "伍拾到陆拾"

# 预处理数据，将大写转化为小写
# 下面代码仅作为演示，实际可以使用正则匹配一次性替换
new_s = s.replace("伍", "五").replace("陆", "六").replace("拾", "十")
# new_s: 五十到六十

output = cn2an.transform(new_s, "cn2an")
# output: 50到60
```

**Comment by lihuacai168** [comment]
> 你可以尝试先做预处理，然后再使用 transform

嗯嗯，看来只能先预处理了。

**Comment by ZORfree** [comment]
有一个需求不知道之前有没有别人提过

影视剧的实体中的数字转换

其实大部分都是直结转换就行了

如电影2012，说法就是电影二零一二

但是也有需要转换的，如失恋33天，说法就是失恋三十三天

不知道这类的能不能是实现

**Comment by Ailln** [comment]
@ZORfree 目前这个库主要功能为转化，而智能识别转化的类型，暂时需要手动预处理。

**Comment by wsgfz** [comment]
> @wsgfz v0.4.2 版本上线，该功能已加入，请更新后使用。
> 
> ![image](https://user-images.githubusercontent.com/7982046/85910909-21ad7180-b854-11ea-9355-27d4e01533f0.png)

赞 多谢~

**Comment by waterglass** [comment]
可以支持标准的财务金额写法吗，比如 `12` 转换成 `壹拾贰圆`

**Comment by Ailln** [comment]
@waterglass 可以，下个小版本安排。

**Comment by Ailln** [comment]
@waterglass v0.5.9 已经更新。

1. 完成 `12` => `壹拾贰元整`;
2. 我看到一些规范使用了单位`元`，你可以尝试自行转化 `"壹拾贰元整".replace("元", "圆")`。

**Comment by waterglass** [comment]
好的，谢谢~

> @waterglass v0.5.9 已经更新。
> 
> 1. 完成 `12` => `壹拾贰元整`;
> 2. 我看到一些规范使用了单位`元`，你可以尝试自行转化 `"壹拾贰元整".replace("元", "圆")`。

**Comment by Orangeices** [comment]
人民币大写 --> 阿拉伯数字  支持角和分。

**Comment by Ailln** [comment]
@Orangeices v0.5.10 已经更新，支持大写中的「元角分」。

**Comment by Orangeices** [comment]
@Ailln 非常感谢！！ 
但还是有点问题，`output = cn2an.cn2an("拾贰元",)` ，报错了  `ValueError: 当前为strict模式，输入的数据不在转化范围内：元！`。可能是那个正则写的有点儿问题：
```
# 处理元角分
yjf_pattern = re.compile(fr"^.*?[元圆][{self.all_num}]角([{self.all_num}]分)?$")
```
再次感谢！！

**Comment by Ailln** [comment]
因为在大写人民币转化时，如果没有角分的数字，需要带“整”或者“正”才对，因此`拾贰元`是不允许的格式，可以试试`拾贰元整`或者`拾贰元五角`。

我觉得未来可以考虑在 normal 的模式下，可以接受`拾贰元`的格式。

**Comment by Ailln** [comment]
@180909 具体一点，给些期望转化的输入输出。

**Comment by 180909** [comment]
@Ailln 
比如：`半百`->`50`;`半块`->`0.5`

**Comment by Ailln** [comment]
`半百`可以考虑，但`半块`的需求太少见了，建议使用 replace 直接替换。 @180909

**Comment by Ailln** [comment]
这个issue太长了，每次翻都不方便，大家以后有新需求就提一个新的 issue 吧。

**Comment by Ailln** [comment]
@Orangeices v0.5.11 cn2an 支持在 normal 模式下可以转化 `拾贰元` ，可以不必须为 `拾贰元整` 的格式。
