### ISSUE TITLE
程序封装到docker里出现 no module named yaml

### ISSUE THREAD

**Issue by Ailln** [Ailln/cn2an#18]
@Ailln 我现在把程序封装到docker里面，用docker compose 运行，但是在下载cn2an的时候一直报错：
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c6k7n574/cn2an/setup.py", line 5, in <module>
        from cn2an import version
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/__init__.py", line 2, in <module>
        from . import cn2an
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/cn2an.py", line 3, in <module>
        from . import utils
      File "/tmp/pip-install-c6k7n574/cn2an/cn2an/utils.py", line 3, in <module>
        import yaml
    ModuleNotFoundError: No module named 'yaml'

我的requirements文件已经包含了pyyaml 和cn2an。
gunicorn
uvicorn
loguru
pandas
sqlalchemy
redis
datetime
configparser
PyYAML>=5.1
cn2an
想问下这是怎么回事呢 ？

_Originally posted by @huanggengkeng in https://github.com/Ailln/cn2an/issues/10#issuecomment-563623706_

**Comment by huanggengkeng** [comment]
我已经解决问题了。把pyyaml 和cn2an 从requirements 文件分离出来，从dockerfile 执行pip install 命令，如下：
RUN pip3 install -I PyYAML>=5.1
RUN pip3 install -I cn2an
RUN pip3 install -I -r requirements.txt 

PS :发现 直接执行：“RUN pip3 install -I PyYAML>=5.1 cn2an” 这一条命令也是报同样的错误

**Comment by huanggengkeng** [comment]
感谢 @Ailln 的关注

**Comment by Ailln** [comment]
我对 docker 不是很熟悉，对于这个问题我的想法是先验证 yaml 包是否真的存在。

比如使用 `pip list` 确定是否 yaml 已经成功安装？

**Comment by Ailln** [comment]
我在 cn2an 的 requirements.txt 已经添加了 pyyaml 的依赖，正常来说安装 cn2an 前应该会先安装 pyyaml。

你能把完整的安装日志发出来吗？不仅仅是报错这部分日志。

**Comment by huanggengkeng** [comment]
requirement.txt 如下：
PyYAML>=5.1
cn2an
loguru
pandas

对应的错误的日志如下：
Collecting PyYAML>=5.1 (from -r requirements.txt (line 1))
  Downloading https://mirrors.aliyun.com/pypi/packages/8d/c9/e5be955a117a1ac548cdd31e37e8fd7b02ce987f9655f5c7563c656d5dcb/PyYAML-5.2.tar.gz (265kB)
Collecting cn2an (from -r requirements.txt (line 2))
  Downloading https://mirrors.aliyun.com/pypi/packages/58/44/f59f4bbb9ff0bcb6cdb69f1aa0be5010a42a091cadc7ef9769f9c850942c/cn2an-0.3.8.tar.gz (85kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rpm5mbdd/cn2an/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rpm5mbdd/cn2an/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-rpm5mbdd/cn2an/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rpm5mbdd/cn2an/setup.py", line 5, in <module>
        from cn2an import version
      File "/tmp/pip-install-rpm5mbdd/cn2an/cn2an/__init__.py", line 2, in <module>
        from . import cn2an
      File "/tmp/pip-install-rpm5mbdd/cn2an/cn2an/cn2an.py", line 3, in <module>
        from . import utils
      File "/tmp/pip-install-rpm5mbdd/cn2an/cn2an/utils.py", line 3, in <module>
        import yaml
    ModuleNotFoundError: No module named 'yaml'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Ailln** [comment]
我暂时还看不出什么问题，你能把执行 `pip list` 的结果发出来一下吗？

**Comment by huanggengkeng** [comment]
docker 的问题哈。我上面写了解决方案咯

**Comment by Ailln** [comment]
好的，你问的这个问题引出了一个潜在问题：为什么 pyyaml 在依赖中却需要先手动安装？

我会在后续的版本中尝试解决这个问题。

**Comment by Ailln** [comment]
这个问题在 `0.3.9` 版本中已被修复。
