### ISSUE TITLE
测试“ cn2an(“三万亿”）的问题

### ISSUE THREAD

**Issue by Ailln** [Ailln/cn2an#19]
测试“ cn2an(“三万亿”）,也是转化错误哦，等于 30000000000000000
cn2an("三千万亿") ，等于3000000000000000，也不对哦
@Ailln

_Originally posted by @huanggengkeng in https://github.com/Ailln/cn2an/issues/10#issuecomment-573267505_

**Comment by Ailln** [comment]
![image](https://user-images.githubusercontent.com/7982046/72199990-9f381d80-347e-11ea-897e-fa04b3342288.png)

你能把上图的步骤的结果发上来吗？

**Comment by huanggengkeng** [comment]
![image](https://user-images.githubusercontent.com/9609594/72200093-e70b7480-347f-11ea-8c03-461e92429e79.png)

**Comment by Ailln** [comment]
升级一下版本，先前的版本不支持。
