### ISSUE TITLE
不支持数字与中文单位混合金额转换

### ISSUE THREAD

**Issue by yoyo182487329** [Ailln/cn2an#2]
# 背景
大部分语音软件将中文金额转为文字时，会输出阿拉伯数字与中文单位的混合，如：
语音输入“一百万”，文字将转为“100万”
语音输入“十亿三千万”，文字将转为“十亿3000万”
语音输入“一百万两千”，文字将转为“100万两千”

# 预期的feature
~~~
cn2an.cn2an("100万")
>>> 1000000
~~~
~~~
cn2an.cn2an("十亿3000万")
>>> 1030000000
~~~
~~~
cn2an.cn2an("100万两千")
>>> 1002000
~~~

# 目前的bug
在中文口语里，只有两个相邻单位的数字，人们往往会直接省略掉后一个单位，如：
标准语句：“三万五千”，口语：“三万五”
标准语句：“两千六”，口语：“两千六”
标准语句：“一百二十”，口语：“一百二”
当输入的末尾不存在单位时，目前cn2an是存在bug的：
~~~
cn2an.cn2an("三万五")
>>> 30005 #理论值 35000
~~~
~~~
cn2an.cn2an("两千六")
>>> 2006 # 理论值 2600
~~~
~~~
cn2an.cn2an("一百二")
>>> 102 # 理论值 120
~~~

# suggestion
## suggestion_1
通过使用正则表达式去匹配“个”“十”“百”“千”“万”“亿”之前的汉字或阿拉伯数字，然后再进行转换。
## suggestion_2
中文部分的实现可参照[该链接](https://segmentfault.com/a/1190000013048884)
数字部分的提取可参照suggestion_1

**Comment by kinggreenhall** [comment]
我有些不太清楚的地方，想和你讨论一下具体需求。

### 需求描述

**功能：**
中文金额 -> 阿拉伯数字 + 中文单位

**实例：**
1. 一百万 -> 100万
2. 十亿三千万 -> 10亿3000万
3. 一百万两千 -> 100万2000

请问我这样理解对吗？

### 回复

> 建议在字典中加入对数字的映射。

这句能再描述的详细一些吗？

**Comment by kinggreenhall** [comment]
@yoyo182487329 收到，我会尽快反馈你。

另外，你有考虑自己来实现这部分功能吗？

**Comment by kinggreenhall** [comment]
我打算编写一个`auto2an`的模块，但处理它的优先级不会太高。

**Comment by martinluck** [comment]
File "C:\Users\testter\AppData\Local\Temp\pycharm-packaging\cn2an\setup.py", line 21, in <module>
        long_description=open("./README.md", "r").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 62: illegal multibyte sequence

这个错误怎么解决？我当前Python 3.6版本，试过3.7也是有这个错误

**Comment by HaveTwoBrush** [comment]
请开一个新的 issue 提问。

**Comment by Ailln** [comment]
v0.3.11 已经上线，支持混合转化功能。

```python
output = cn2an.cn2an("1百23", "smart")
print(output)
# 123
```
