### ISSUE TITLE
>>> cn2an.transform("十七十八","cn2an") 

### ISSUE THREAD

**Issue by leizingyiu** [Ailln/cn2an#24]
'88'

😢

**Comment by Ailln** [comment]
这种模式没有被 strict 的过滤器识别掉，我会尽快修复它。

**Comment by Ailln** [comment]
目前该项目只具有对正确模式正确转化的功能，具有对少量错误模式进行识别的功能，整体性的模式错误识别会放到下个大版本中做。

**Comment by Ailln** [comment]
@leizingyiu ，在 v0.4.3 版本中，我尝试对核心代码进行了重构。

其中很重要的一个功能是**对错误输入的准确识别**，当前在任何模式下，输入`十七十八`都会直接报错。

![image](https://user-images.githubusercontent.com/7982046/85933255-91306900-b907-11ea-835b-b8a2e87169d1.png)

对于这种情况的我的建议是做好异常判断，未来可能会在 smart 模式加入对类似不规则数据的处理。
