### ISSUE TITLE
希望可以最大支持到千兆

### ISSUE THREAD

**Issue by RS-Nocsi** [Ailln/cn2an#29]
我希望可以最大支持到千兆，虽然目前的大小已经够了，但我要处理的数实在是太大太大了
谢谢啦！

**Comment by Ailln** [comment]
`兆`这个单位在很多语境下都不同，比如某些情况下 `兆 = 万亿`，当前支持到`千万亿`，即支持`千兆`。

这个库最初设计时，目标支持到 10 的 32 次方，但是由于歧义使我放弃的后面的长度。

能给出一些你需要转化的样例吗？我们可以一起探讨一下。

**Comment by RS-Nocsi** [comment]
> `兆`这个单位在很多语境下都不同,比如某些情况下 ,当前支持到,即支持。`兆 = 万亿``千万亿``千兆`
> 
> 这个库最初设计时,目标支持到 10 的 32 次方,但是由于歧义使我放弃的后面的长度。
> 
> 能给出一些你需要转化的样例吗?我们可以一起探讨一下

> `兆`这个单位在很多语境下都不同,比如某些情况下 ,当前支持到,即支持。`兆 = 万亿``千万亿``千兆`
> 
> 这个库最初设计时,目标支持到 10 的 32 次方,但是由于歧义使我放弃的后面的长度。
> 
> 能给出一些你需要转化的样例吗?我们可以一起探讨一下。

我要转换的数字是`18446744073709551615`，即2^64 -1 
就是计算国王和大米的故事中所有大米的总数，计算代码已经写完，就是觉得显示阿拉伯数字不直观，想要转换成中文

**Comment by Ailln** [comment]
你可以试试分开转化的思路：

`2^64 -1 = 18446744073709551615`

共有 20 位，我们把它切分成 4 位 + 16 位，中间添加单位「兆」。

1844 => 一千八百四十四
6744073709551615 => 六千七百四十四万零七百三十七亿零九百五十五万一千六百一十五

即：`一千八百四十四兆六千七百四十四万零七百三十七亿零九百五十五万一千六百一十五`

**Comment by RS-Nocsi** [comment]
> 你可以试试分开转化的思路：
> 
> `2^64 -1 = 18446744073709551615`
> 
> 共有 20 位，我们把它切分成 4 位 + 16 位，中间添加单位「兆」。
> 
> 1844 => 一千八百四十四
> 6744073709551615 => 六千七百四十四万零七百三十七亿零九百五十五万一千六百一十五
> 
> 即：`一千八百四十四兆六千七百四十四万零七百三十七亿零九百五十五万一千六百一十五`

秒啊，谢谢大佬

**Comment by Ailln** [comment]
不客气～
