### ISSUE TITLE
“半”，“两”目前不支持识别

### ISSUE THREAD

**Issue by chbambooshoot** [Ailln/cn2an#32]
![image](https://user-images.githubusercontent.com/16066340/110497348-51c24980-8131-11eb-88db-1270f4fdfae7.png)

**Comment by Ailln** [comment]
v0.5.11 support 半/两 in transform.

**Comment by zhengweiHuang** [comment]
v0.5.17 含 半/二  句子经过transform 变成 零点五/两

**Comment by zhengweiHuang** [comment]
> v0.5.17 含 半/两 句子经过transform 变成 零点五/二

v0.5.11也是， 这两个字 实际无需转换
