### ISSUE TITLE
报告数字与中文混合情况下的问题

### ISSUE THREAD

**Issue by weiwchu** [Ailln/cn2an#36]
**Describe the bug**
"各地累计报告接种新冠病毒疫苗104974.4万剂次"
新闻联播播音员说的是：
`**十亿四千九百七十四**点四万剂次`
但是cn2an的输出是
`十万零四千九百七十四点四万`

**Desktop (please complete the following information):**
 - OS: Linux
 - Version cn2an==0.5.11

**Comment by Beants** [comment]
这是播音员念错了吧
应该有如下两种念法：
* 十亿四千九百七十四万四千
* 十万零四千九百七十四点四万

建议参考小学课本 https://github.com/Beants/cn2an/blob/master/src/%E5%A4%9A%E4%BD%8D%E6%95%B0%E7%9A%84%E8%AF%BB%E6%B3%95.pdf
