### ISSUE TITLE
关于中文数字中省略”零“的情况

### ISSUE THREAD

**Issue by lidh15** [Ailln/cn2an#44]
您好，在测试”一亿两千万三百万四百五十六“时无法解析，
我测试了一下要写成”一亿两千三百万零四百五十六“才行，
虽然我也知道小学就教过这里要写这个”零“，但是这个地方甲方爸爸不想写，出事了乙方全责，您看有什么办法可以支持一下吗？

**Comment by Ailln** [comment]
可以尝试先做预处理，把零补上后再做转化。
