### ISSUE TITLE
库本身的建议

### ISSUE THREAD

**Issue by guanquanchen** [Ailln/cn2an#48]
程序是基于文件的，所以我认为程序是一个文件夹系统，最基本的就是这个
他包含代码和资源两个部分，
我在打包的时候，就发现 文件夹系统本身会发生变化，这种比较头疼的问题，还需要打包得到exe的人自己处理。

要是能够直接一次行代码就好了，  老哥可以自己保留  相关的资源文件，如果发现库被打包了，就在临时文件夹中创建对应的文件路径体系，把资源放进去。

**Comment by Ailln** [comment]
感谢建议，有空我会仔细看看相关问题～
