### ISSUE TITLE
打包成功运行失败

### ISSUE THREAD

**Issue by cddldg** [Ailln/cn2an#49]
File "PyInstaller\loader\pyimod02_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI200602\\cn2an\\config.yaml'

**Comment by Ailln** [comment]
#47 你先参考一下这个，近期会修复这个问题。

**Comment by Ailln** [comment]
`v0.5.19` 已修复，请升级后再次尝试。
