### ISSUE TITLE
簡體('参':\u53c2)不在conf.py內

### ISSUE THREAD

**Issue by thisisanOldMan** [Ailln/cn2an#54]
**Describe the bug**
conf.py of the proces module map tranditional chinese word(參:\u53c3) to simplified chinese word('参':\u53c2) through the dictionary , T2S_DICT .

cn2an.py translate tranditional chinese word(參:\u53c3) to simplified chinese  through proces.preprocess file , then use conf.py in cn2an module to convert chinese number to arabic numeral .

Howerver , in  conf.py , there isn't corresponding simplified chinese word('参':\u53c2) in conf.py of cn2an module , which leads to conf.py can identify ('参':\u53c2) and convert it to arabic numeral .

**To Reproduce**
cn2an.cn2an('參','smart')

**Desktop (please complete the following information):**
 - OS: Window
 - Browser : chrome

**Comment by Ailln** [comment]
数字3的大写为「叁」
