### ISSUE TITLE
千和百识别不了

### ISSUE THREAD

**Issue by jackyjinjing** [Ailln/cn2an#60]
import cn2an

output2 = cn2an.transform("5百左右的鞋子")
output5 = cn2an.transform("千元以上的鞋子")

print(output2)
print(output5)

输出如下：
WARN: 不符合格式的数据：百
WARN: 不符合格式的数据：千
5百左右的鞋子
千元以上的鞋子

**Comment by Beau-xu** [comment]
针对第一种数字＋汉字的组合形式，最近的更新可以通过`an2cn.an2cn()`在短语层面转换，但是还不能通过`transform`在句子中转换。我目前是通过两次转换解决的，可以凑合一下：

```python
query = "5百左右的鞋子"
query = cn2an.transform(query, 'an2cn')
query = cn2an.transform(query)    # '500左右的鞋子'
```

第二种情况暂时无解。
