### ISSUE TITLE
非数字中文转成数字：我的两个钱包一共有：九百九十八元和五百六十二块钱。他们一起构成了我的资产

### ISSUE THREAD

**Issue by voyager0003** [Ailln/cn2an#66]
**Describe the bug**
非数字中文转成数字

**To Reproduce**
1. run following code:
```
    import cn2an

    result = cn2an.transform(input_sentence)
    print(result)
```
2. See error

**Expected behavior**
我的2个钱包一共有：998元和562块钱。他们一起构成了我的资产

**Screenshots**
![image](https://github.com/Ailln/cn2an/assets/15920086/be754d28-7e4e-460c-b54c-66153eb61a71)

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04
 - Version cn2an 0.5.22

**Comment by Ailln** [comment]
`transform` 这个函数作为实验性功能，只是单纯做了文字匹配，并未对语义进行识别，暂时没有找到简单有效的办法。

**Comment by voyager0003** [comment]
我找到了一个短期方案：先调用transform，然后维护一个不需要转阿拉伯数字的列表，比如：【1起: 一起，1共: 一共，1道: 一道】，然后遍历转换后的字符串，替换回去。就是需要人工维护这样一个列表。😀
