### ISSUE TITLE
能否实现“二百八”转换为208的功能？

### ISSUE THREAD

**Issue by MrMoggy** [Ailln/cn2an#73]
我在做古籍普查工作，在汉文古籍中，表述卷次一般会写为“二百八卷”，表示共有208卷，我需要将汉字数字转为阿拉伯数字，并统计总卷数。

我知道在您的设计中，这样的汉字数字，会转为280。不知可否设计另外一种转换的模式，实现这样的结果。

图片只是示例，这里表示的是第108卷
![5コマ](https://github.com/Ailln/cn2an/assets/85000446/45a69c49-f2c7-4cda-97d8-3804dc049a37)

**Comment by Ailln** [comment]
还有别的特殊转化吗？（也许这里其实可以用个正则提前转一下就行。

**Comment by MrMoggy** [comment]
> 还有别的特殊转化吗？（也许这里其实可以用个正则提前转一下就行。

有时候会出现“百八卷”，表示有108卷，除此之前，应该没有其他特殊情况了。

**Comment by Ailln** [comment]
比如这样做一个预处理：

```python
import re

text_list = ["一百八十", "一百八"]
for text in text_list:
    new_text = re.sub(r"百([一二三四五六七八九])(?!十)", r"百零\1", text)
    print(text, new_text)
```

结果：
```bash
一百八十 一百八十
一百八 一百零八
```

**Comment by MrMoggy** [comment]
非常感谢回复🙏

**Comment by Ailln** [comment]
不客气
