### ISSUE TITLE
请不要在依赖中包含 setuptools

### ISSUE THREAD

**Issue by trim21** [Ailln/cn2an#82]
现在pypi上的wheel是依赖setuptools的，是从这里引入的 https://github.com/Ailln/cn2an/blob/40b6e3f53815be00af0392d40755c24401c7c61c/setup.py#L38

但这个package实际运行的时候并不会调用setuptools，只是需要setuptools来构建wheel，请把setuptools放到 [requirements_dev.txt](https://github.com/Ailln/cn2an/blob/master/requirements_dev.txt) 文件中

**Comment by Ailln** [comment]
get

**Comment by Ailln** [comment]
v0.5.23 已经删除。
